# Generated by Django 2.2.7 on 2019-11-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(max_length=50, unique=True)),
                ('arrival', models.CharField(max_length=50, unique=True)),
                ('distance', models.FloatField()),
                ('carbon', models.FloatField()),
            ],
        ),
    ]
